{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.oleslieo",
    "module": "shooter-autotune",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.oleslieo",
          "module": "shooter-autotune-core",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "shooter-autotune-0.1.3.aar",
          "url": "shooter-autotune-0.1.3.aar",
          "size": 27148,
          "sha512": "bc1731f50c57696174a1ee82a523a8a506bcc35a79beea4029b172dc68169c9ade8cc8f3a90948e250ede2fe15ade1a808593c37279eed9f37f310b8d99f6999",
          "sha256": "70b78d880780acf21a1924ff913f86bfea98d6cbe543a1e7ad1981466a5f93ea",
          "sha1": "510b3c41697ad28ec2bc8c83c9f0a920b388be1c",
          "md5": "c1d4d74b05053d3bae3ae0d19b872390"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.oleslieo",
          "module": "shooter-autotune-core",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "shooter-autotune-0.1.3.aar",
          "url": "shooter-autotune-0.1.3.aar",
          "size": 27148,
          "sha512": "bc1731f50c57696174a1ee82a523a8a506bcc35a79beea4029b172dc68169c9ade8cc8f3a90948e250ede2fe15ade1a808593c37279eed9f37f310b8d99f6999",
          "sha256": "70b78d880780acf21a1924ff913f86bfea98d6cbe543a1e7ad1981466a5f93ea",
          "sha1": "510b3c41697ad28ec2bc8c83c9f0a920b388be1c",
          "md5": "c1d4d74b05053d3bae3ae0d19b872390"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shooter-autotune-0.1.3-sources.jar",
          "url": "shooter-autotune-0.1.3-sources.jar",
          "size": 9924,
          "sha512": "4c6e3dc04d92777ee500389a50c23f29330ac60603ca32b711c8ead692ed82ecee0099c299b223a72a3fd2496ca3ac0e52431a045f3dc6c751bdea933bbd521d",
          "sha256": "d37174eb96f4401f44e0c2822bf72aec5a922f1dfdacb5e40524552094859d3e",
          "sha1": "686a4d10cce6d6edb9c73eec786a245879b53c23",
          "md5": "98bbdb49a8afd5a661a81b4ba9176deb"
        }
      ]
    }
  ]
}
